version: '3.8'

services:
  postgres-messenger:
    image: postgres:latest
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-messenger-data:/var/lib/postgresql/data

  postgres-messenger-test:
    image: postgres:latest
    environment:
      POSTGRES_DB: messenger-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-messenger-test-data:/var/lib/postgresql/data

volumes:
  postgres-messenger-data:
  postgres-messenger-test-data: